---
# tasks file for homework-ansible-role-build
- name: ensure packages are installed
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
- name: get sources for build from github
  git:
    repo: "{{ repo_path }}"
    dest: "{{ build_path }}"
- name: ensure docker-py is present
  pip:
    name: "{{ module }}"
- name: enable and start service
  service:
    name: "{{ service }}"
    state: started
    enabled: yes
- name: Log into DockerHub
  docker_login:
    username: "{{ dockeruser }}"
    password: "{{ dockerpass }}"
    email: "{{ dockeremail }}"
- name: build and containerize application
  docker_image:
    path: "{{ build_path }}"
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    push: yes
- name: delete temp files
  file:
    path: "{{ build_path }}"
    state: absent
